### ISSUE TITLE
Selector as undefined

### ISSUE THREAD

**Issue by arunagiritm** [vsternbach/angularjs-typescript-webpack#1]
I cloned this repo. The routing is not happening for "view1" or "view2". On debugging the selector is coming as 'undefined'

![image](https://cloud.githubusercontent.com/assets/11343122/25993576/02378d6e-3728-11e7-9625-b5eb049d9c70.png)

**Comment by vsternbach** [comment]
I am sorry, but routing in the example is not in use, it's just leftovers from the previous project where I was playing with decorating ui-router

**Comment by smololath** [comment]
So, how to fix this? I am getting selector as undefined too.

**Comment by vsternbach** [comment]
not relevant anymore, updated the project as angular tour of heroes example
