### ISSUE TITLE
Why use angular-cli-tools instead of angular-cli?

### ISSUE THREAD

**Issue by JoeFirebaugh** [vsternbach/angularjs-typescript-webpack#35]
I'm sorry to open this is an issue, but I'm really trying to understand if this recipe for building an NG 1.7 project is the best solution for us.

Is there a technical reason for using `angular-cli-tools` instead of `angular-cli`?   I'm wanting to upgrade our NG 1.5 project to 1.7 and everything you've done so that migrating to NG7 will be simpler and possibly even piece meal.

Thanks!

**Comment by vsternbach** [comment]
angular-cli doesn't support angularjs, it's just for convenience here when you're still developing in angularjs and want an easier way to create new components
