### ISSUE TITLE
Angular ui router route change

### ISSUE THREAD

**Issue by Polyterative** [vsternbach/angularjs-typescript-webpack#4]
Getting this error while downloading dependencies from NPM

> pm WARN deprecated angular-ui-router@1.0.3: This npm package 'angular-ui-router' has been renamed to '@uirouter/angularjs'. Please update your package.json. See https://ui-router.github.io/blog/uirouter-scoped-packages/

Now I'm okay with fixing it in my project but it would be nice to update the repo

**Comment by Polyterative** [comment]
Gave up/abbandoned angularjs

**Comment by vsternbach** [comment]
Don't see the point of using it for new projects, it's mostly for existing projects to help setup the project, I will update it soon, without dependencies on other not-relevant third party modules
